### ISSUE TITLE
feat: 결제 로직 변경하기

### ISSUE THREAD

**Issue by clean2001** [samtuap/dongsanginong-server#248]
## 이슈 설명

현재 비동기로 처리되고 있는 결제를 동기로 변경

## ✅ Todo 

- [ ] 결제처리 비동기 -> 동기로 변경
- [x] receiptId와 orderId를 동일하게 하게
- [ ] `makeOrder`에서 orderCount가 올라가도록 처리
- [x] 첫 결제 uri 변경 (포스트맨도 변경하기)
