### ISSUE TITLE
fix: 결제 관련 코드 수정

### ISSUE THREAD

**Issue by clean2001** [samtuap/dongsanginong-server#318]
## 이슈 설명

결제 엔티티에 주문 번호 추가

## ✅ Todo 

- [ ] 결제 엔티티에 주문 번호 추가
- [ ] 결제 정보 response dto에 주문 번호 추가
- [ ] 결제 시에 세일 가격이 적용되도록 변경
